language: php

dist: trusty

branches:
  only:
    - master
    - v1.x

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: 5.4

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -q
  - composer self-update

install:
  - composer update

script:
  - vendor/bin/phpunit tests
